### ISSUE TITLE
Progress Bar not working in 3.0.10

### ISSUE THREAD

**Issue by BosonHair** [datawhores/OF-Scraper#160]
Hello,
I noticed the progress bar seems stuck for me on 3.0.10. I can see the temp files being downloaded but no progress.
![Screen Shot 2023-08-08 at 12 02 25 PM](https://github.com/datawhores/OF-Scraper/assets/139021271/aea53eeb-e595-4158-8e2e-f4b273cb7dba)

**Comment by BosonHair** [comment]
Then it'll randomly catch up. I assume the failures are drm?

![Screen Shot 2023-08-08 at 12 08 12 PM](https://github.com/datawhores/OF-Scraper/assets/139021271/a3921ef9-1eda-4bc3-b2cf-1168c61260fb)

**Comment by datawhores** [comment]
That is a lot of failures
I would run with --output debug to see why

I think their might be multiple issues causing failed downloads

**Comment by hiddenGoldNova7** [comment]
Hi @BosonHair 
do you use 'download_type' to name your files? I think the reason why so many downloads failed is because of this. Because I had the same error when I used that, when I took it out everything worked without problems.

@datawhores  FYI
![Screenshot 2023-08-08 191141](https://github.com/datawhores/OF-Scraper/assets/36936998/0a351211-425a-47bb-b002-5ddb2faae31c)

**Comment by BosonHair** [comment]
Ah, I see the updated config with those settings. I'll leave them off.

Regarding the errors, I'll make a new ticket but I'm not using download_type:
`      "dir_format": "{model_username}/{mediatype}/{date}",
        "file_format": "{media_id}.{ext}",
        "textlength": 25,`
