### ISSUE TITLE
# Missing accounts from lists

### ISSUE THREAD

**Issue by 6R1M4C3** [datawhores/OF-Scraper#238]
**Describe the bug**
I have noticed that when I have no filters set on the config of what I want to show, it doesn't actually show everyone i have been subscribed to or are subscribed to and it doesn't always show users I'm no longer subscribed to but have purchased content from privately, it also doesn't show deleted users who you have purchased from but have since deleted their accounts.

the script on use says a total of 95 both active and not active, but on the website it reports a total of 117 

**To Reproduce**
Steps to reproduce the behaviour:
Hint: set the config for search to both subbed and un-subbed free and paid, 

**Expected behaviour**
show a list of everyone past and present specifically the premium paid users.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version latest version through pipx

**Comment by CannotTouch** [comment]
https://github.com/datawhores/OF-Scraper/issues/224

**Comment by 6R1M4C3** [comment]
> #224

I cant even get the scrape entire paid page to work.

**Comment by drnoob-afk** [comment]
I found a way to pass over this issue : 
the offset in the subscription list API on the site goes further than the amount of existing subscriptions of the account. 
In my case, I have 260 subscriptions and while scrolling, the offsets goes up to 290. 
A hotfix is to edit the line 29 in subscription.py : 
    offsets = range(0, subscribe_count, 10)
into : 
    offsets = range(0, subscribe_count*2, 10)

that way, we send requests with up to twice the amount of subscribe count you have and you're sure to retrieve them all. 

The right fix would be to keep increasing the offset until "hasMore" is false in the response. but I don't have the python knowledge or the patience to try to do it. 
I've manually edited the file in my local copy of ofscraper and it works, i get the full 260 subscription instead of the first 220 or so of the list

**Comment by 6R1M4C3** [comment]
> I found a way to pass over this issue : the offset in the subscription list API on the site goes further than the amount of existing subscriptions of the account. In my case, I have 260 subscriptions and while scrolling, the offsets goes up to 290. A hotfix is to edit the line 29 in subscription.py : offsets = range(0, subscribe_count, 10) into : offsets = range(0, subscribe_count*2, 10)
> 
> that way, we send requests with up to twice the amount of subscribe count you have and you're sure to retrieve them all.
> 
> The right fix would be to keep increasing the offset until "hasMore" is false in the response. but I don't have the python knowledge or the patience to try to do it. I've manually edited the file in my local copy of ofscraper and it works, i get the full 260 subscription instead of the first 220 or so of the list

I'm not seeing this anywhere inside the file, what version are you using? my sub.py file doesn't even mention these within it.

**Comment by datawhores** [comment]
I'll leave this open, but I not sure if it actually an issue 
since the number reported on onlyfans for all accounts is not accurate

It seemingly includes deleted account
Previously you could load the entire page, and search for something to confirm

But now only part of the page is exposed at a time, so the only way to know is to look at the network tab, and watch the return values from the subscribes api, and match that to what should be returned to the actual number returned

**Comment by datawhores** [comment]
Make sure you are updated to the newer version
Some issue seem to stem from using older version

If you want to utilize older versions of the script, feel free to utilize the suggestion here
https://github.com/datawhores/OF-Scraper/issues/238#issuecomment-1782244904

**Comment by 6R1M4C3** [comment]
> > > Make sure you are updated to the newer version Some issue seem to stem from using older version
> > > If you want to utilize older versions of the script, feel free to utilize the suggestion here [#238 (comment)](https://github.com/datawhores/OF-Scraper/issues/238#issuecomment-1782244904)
> > 
> > 
> > Pipx upgrade states ofscraper is already at latest version 3.2.4, has the pipx package not been pushed the new versions?
> 
> They have the latest is 3.4.4
> 
> What shows usually depends on what version of Python you have usually
> 
> Run pipx with the --verbose flag will tell you what python it is using to make the virtualenv

it claims its using 3.10 as the version
