### ISSUE TITLE
Option to only check/download most recent content?

### ISSUE THREAD

**Issue by dunngitter** [datawhores/OF-Scraper#305]
Maybe this already exists and I just haven't been able to find it, but it would be really great if there was an arg or setting that I could set such that on each run, only the most recent content from each existing model is looked at by the script at all.

Instead of fetching and checking every post/message/etc. for each model, in this mode the script would pull content in recent order, most recent first, and stop as soon as it encounters a piece of content that has already been downloaded previously. This would be much faster for all models that have been previously scraped, as only a few messages/posts/etc. would have to be fetched and compared (if you run the script frequently)

I run the script in daemon mode with an interval of 2hrs, but each execution still takes forever and makes tons of requests to OF servers, even though most of the time only one or two pieces of content are downloaded.

Is this doable?

**Comment by Jarsky** [comment]
use the --after <date> argument in your script. its detailed [in the wiki](https://of-scraper.gitbook.io/of-scraper/batch-scraping-and-bot-actions/selecting-posts)

e.g you could run ofscraper --daemon --username ALL --posts ALL --after 20240101

You could generate the after date in your script, if you want it to always check for example the last week based off the current date. e.g something like this:

```
#!/bin/bash
# Days to subtract
cutDays=7
$dynDate=$(date -d "$cutDays days ago" "+%Y%m%d")

ofscraper --daemon --username ALL --posts ALL --after "$dynDate"
```

which today (15/01/2023 where I am) would generate this:
`ofscraper --daemon --username ALL --posts ALL --after 20240108`

Instead of running it as a daemon though you'd probably want to run it as a task (task scheduler or cron depending on your OS)
Personally I have mine in Docker, and use a Screen session to run it. So with the change mine would look something like this:

```
#!/bin/bash

# Variables
screenName="ofscraper"
dockerContainer="of-scraper"
# Number of days to subtract from the current date
cutDays=7

# Script

dynDate=$(date -d "$cutDays days ago" "+%Y%m%d")

if [ "$1" == "start" ]; then
    # Start of-scraper
    screen -X -S "$screenName" quit
    screen -S "$screenName" -d -m docker exec $dockerContainer ofscraper --username ALL --posts ALL --after "$dynDate" -ts
    echo "OF-Scraper started in screen session '$screenName'."
elif [ "$1" == "stop" ]; then
    # Stop of-scraper
    screen -X -S "$screenName" quit
    echo "OF-Scraper terminated"
elif [ "$1" == "restart" ]; then
    # Restart of-scraper
    screen -X -S "$screenName" quit
    screen -S "$screenName" -d -m docker exec $dockerContainer ofscraper --username ALL --posts ALL --after "$dynDate" -ts
    echo "OF-Scraper restarted in screen session '$screenName'"
else
    echo "Usage: $0 [start|stop|restart]"
    exit 1
fi
```
I can then run that manually e.g ./ofscraper.sh start; or I can schedule it in CRON
For example:

```
sudo crontab -e
0 */2 * * *     cd /home/user/scripts/of-scraper && ./ofscraper.sh start
```

**Comment by datawhores** [comment]
This is already included 
But only works for timeline,archived message
Other media has too little to make it worth it 
Or had to be pulled from newest to oldest

**Comment by datawhores** [comment]
If it is not working then your probably not on the latest version or media is missing

If you provide a log of one of the long runs it should say why
